### ISSUE TITLE
Tracking Detroit/Chicago difference

### ISSUE THREAD

**Issue by erhla** [erhla/ptap#10]
input_data no longer has appeal_type generated from selecting the cook/detroit button at the beginning of the app.

After fix---remove hotfix line 13 of mainfct.py

**Comment by erhla** [comment]
Note that this may be an issue only with the cook section of the app

**Comment by erhla** [comment]
@austinzhang1018 

Would it be easier if we just pass the current url of the browser to the backend? I could easily use that to determine the current locale.

**Comment by erhla** [comment]
See api.py line 21 for current fix: CURRENT_CITY = 'detroit_single_family'

**Comment by austinzhang1018** [comment]
Added appeal_type to data and removed hotfix
