### ISSUE TITLE
MVP

### ISSUE THREAD

**Issue by erhla** [erhla/ptap#7]
For MVP,
- [ ] Split up the pages

# Page 1
- [x] Add title "Property Tax Appeal Project: Automated Appeal System"
- [x] Remove address option from page 1 (input Pin only)
- [x] Add three radio buttons to select type of appeal (Cook County Single Family, Cook County Condo, Detroit Single Family)
- [x] "Enter homeowner information"
- [x] Start with name, email, address/zip (will autofill this eventually), phone, email

# Page 2
- [x] Add title "Select relevant comparables"
- [x] Add "Generate Appeal"

# Autofilier
- [ ] Link and fill out appeal.

**Comment by erhla** [comment]
I made the repository public and it should be here now: https://erhla.github.io/ptap/

**Comment by erhla** [comment]
small bug---column names are not displayed in the order I'm looking for in the app due to conversion from df to dict. Would ordered dict be the solution?

**Comment by austinzhang1018** [comment]
I'm currently parsing the headers from the dictionary passed in, and I'm not sure if the order would be preserved from python to javascript if you used an ordered dict. If you pass me a field, maybe labeled headers, with a list of string representing the fields in the order you'd like them displayed, then I can guarantee the correct arrangement of columns.
