### ISSUE TITLE
First Version

### ISSUE THREAD

**Issue by erhla** [erhla/ptap#8]
# Short Term

- [x] Add attribute 'labeled_headers' : [list of columns in order to be displayed]
- [x] Update Detroit letter with methods/justifications (mean of comps found X)
- [x] Add error handling to flask

# Long Term

- [ ] Add attribute 'prop_info' : 'str' to be displayed at the top of the comparable page (this will include information on whether the homeowner is also the taxpayer, status of homestead exemption, and estimations of neighborhood obsolescence, may be an empty string; lets hide this with some sort of toggle option and show on click)
- [ ] Add summary page (last page)
- [x] Add pin search page (first page, TBD)
- [x] Add sales comps (toggle between assessed value/sales comps?)
- [x] Split Detroit/Cook County---what's the best way to do this.

# Very Long Term

- [ ] Damage input (offer a dropdown menu of damage types---if one is selected create an text input and photo upload input for the damage type---accessibility issues with this, suggested by team that homeowners could text photos as opposed to direct upload)
- [ ] Add to prop_info: Does taxable value equal SEV? Flag as uncapped if it does.

**Comment by erhla** [comment]
in 2de8a90:

initial scope of address finder page 0.

- need python-Levenshtein, fuzzywuzzy
- expecting two inputs, st_num (street number) and st_name (street name)

**Comment by erhla** [comment]
Scope of logger:

- [ ] Backend generate uuid (reset on session) -> store as cookie on front end
- [ ] Generate new log for each step of process with uuid and process_step_id
- [ ] Save in a csv for now

**Comment by austinzhang1018** [comment]
I've added a rudimentary damage input which can be accessed under localhost:3000/test. Currently, you can't enter any data, but it'll help give an idea of the user layout. Should we allow for multiple images for one damage instance.

**Comment by austinzhang1018** [comment]
I added a pin lookup to the form page. Let me know if it's what you had in mind. I think right now it only looks up Detroit pins, so this change breaks the Chicago part of the program. Also, I think it might be a good idea to separate out all of the TODO items into their own separate issues for easier commenting/threads/tracking. From now on, when I work on specific task, I'll set up an issue for it.
